FROM ubuntu:latest                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                              
RUN apt update && apt install  openssh-server sudo -y                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                              
RUN apt-get install boxes --fix-missing -y

RUN apt-get install figlet -y

RUN useradd -rm -d /home/challenge5 -s /bin/bash -u 1000 test01 
RUN useradd -rm -d /home/challenge5 -s /bin/bash -u 1000 test02

RUN echo "figlet -f standard "Challenge 5" | boxes -d scroll" >> home/challenge5/.bashrc 

RUN echo 'challenge5_normaluser:EHC{p4t1eNc3_1s_Th3_k3y}' | chpasswd 
RUN echo 'challenge5_fakeuser:EHC{p4t1eNc3_1s_Th3_k3y}' | chpasswd

COPY flag.txt /home/challenge5/flag.txt

COPY readme.md /home/challenge5/readme.md

RUN chown root:root challenge5
RUN chmod 701 flag.txt
RUN setfacl -m u:test01:rwx flag.txt

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]