FROM ubuntu:latest

RUN apt update && apt install  openssh-server sudo -y

RUN apt-get install boxes --fix-missing -y

RUN apt-get install figlet -y

RUN useradd -rm -d /home/challenge3 -s /bin/bash -u 1000 challenge3

RUN mkdir /home/challenge3/flag

RUN echo "figlet -f standard "Challenge 3" | boxes -d scroll" >> home/challenge3/.bashrc

RUN chown -R root:root /home/challenge3 

ADD flag /home/challenge3/flag

RUN chmod 705 /home/challenge3

RUN echo 'challenge3:EHC{f0rM4t_1s_1mP0rt4n7}' | chpasswd

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]