FROM ubuntu:latest

RUN apt update && apt install  openssh-server sudo -y

RUN useradd -rm -d /home/challenge3 -s /bin/bash -u 1000 challenge3

RUN chown -R root:root /home/challenge3 

ADD flag /home/challenge3/

COPY readme /home/challenge3/

RUN chmod 705 /home/challenge3

RUN echo 'challenge3:EHC{f0rM4t_1s_1mP0rt4n7}' | chpasswd

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]