FROM ubuntu:latest

RUN apt update && apt install  openssh-server sudo -y

RUN useradd -rm -d /home/challenge1 -s /bin/bash -u 1000 challenge1 

RUN chown -R root:root /home/challenge1 
COPY flag.txt /home/challenge1/flag.txt
RUN chmod 705 /home/challenge1
RUN echo 'challenge1:ehcgreat' | chpasswd

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]
