FROM ubuntu:latest

RUN apt update && apt install  openssh-server sudo -y

RUN useradd -rm -d /home/challenge4 -s /bin/bash -u 1000 challenge4

RUN echo "figlet -f standard "Challenge 4" | boxes -d scroll" >> home/challenge4/.bashrc

RUN chown -R challenge4:challenge4 /home/challenge4

COPY flag.txt /home/challenge4/flag.txt

RUN chmod 705 /home/challenge4

RUN echo 'challenge4:EHC{d0_sM4rT3r_n0t_h4rD3r}' | chpasswd

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]